import os
from dotenv import load_dotenv

load_dotenv()

JWT_SECRET = os.getenv("JWT_SECRET")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
JWT_EXPIRE_MINUTES = int(os.getenv("JWT_EXPIRE_MINUTES"))
JWT_REFRESH_EXPIRE_DAYS = int(os.getenv("JWT_REFRESH_EXPIRE_DAYS"))

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_TRACE_TOPIC = os.getenv("KAFKA_TRACE_TOPIC")
KAFKA_TRACE_PERSISTED_TOPIC = os.getenv("KAFKA_TRACE_PERSISTED_TOPIC")
KAFKA_EVAL_TOPIC = os.getenv("KAFKA_EVAL_TOPIC")
KAFKA_SECURITY_PROTOCOL=os.getenv("KAFKA_SECURITY_PROTOCOL")
KAFKA_SSL_CA_FILE=os.getenv("KAFKA_SSL_CA_FILE")
KAFKA_SSL_CERT_FILE=os.getenv("KAFKA_SSL_CERT_FILE")
KAFKA_SSL_KEY_FILE=os.getenv("KAFKA_SSL_KEY_FILE")


POSTGRES_DSN = os.getenv("POSTGRES_DSN")
POSTGRES_POOL_MIN = int(os.getenv("POSTGRES_POOL_MIN"))
POSTGRES_POOL_MAX = int(os.getenv("POSTGRES_POOL_MAX"))
# Path to a CA certificate (.pem) used to verify the Postgres server's TLS
# certificate. When set, the connection uses full verification (verify-full).
# Leave empty/unset for local development (no CA verification).
POSTGRES_SSL_CA_FILE = os.getenv("POSTGRES_SSL_CA_FILE")

POSTGRES_USER_TABLE = os.getenv("POSTGRES_USER_TABLE")
POSTGRES_ORG_TABLE = os.getenv("POSTGRES_ORG_TABLE")
POSTGRES_REVOKED_TOKEN_TABLE  = os.getenv("POSTGRES_REVOKED_TOKEN_TABLE")
POSTGRES_PASSWORD_RESET_TABLE = os.getenv("POSTGRES_PASSWORD_RESET_TABLE")
POSTGRES_GUARDRAILS_TABLE     = os.getenv("POSTGRES_GUARDRAILS_TABLE", "guardrail_policies")

SMTP_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL")
SMTP_FROM_NAME = os.getenv("SMTP_FROM_NAME")
RESEND_API_KEY = os.getenv("RESEND_API_KEY")

PASSWORD_RESET_OTP_LENGTH = int(os.getenv("PASSWORD_RESET_OTP_LENGTH"))
PASSWORD_RESET_EXPIRE_MINUTES = int(os.getenv("PASSWORD_RESET_EXPIRE_MINUTES"))
FRONTEND_BASE_URL = (os.getenv("FRONTEND_BASE_URL") or "").rstrip("/")

# Render "Deploy Hook" URL for the frontend static site. When a blog post is
# published / updated / unpublished we POST here to trigger a rebuild, which
# re-runs the prerender step so the post is baked into static HTML for SEO.
# Optional — publishing still works (fails open) when this is unset.
RENDER_DEPLOY_HOOK_URL = os.getenv("RENDER_DEPLOY_HOOK_URL")

CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST")
CLICKHOUSE_PORT = int(os.getenv("CLICKHOUSE_PORT"))
CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER")
CLICKHOUSE_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD")
CLICKHOUSE_DATABASE = os.getenv("CLICKHOUSE_DATABASE")
CLICKHOUSE_TRACE_TABLE = os.getenv("CLICKHOUSE_TRACE_TABLE")
CLICKHOUSE_TRACE_COSTS_TABLE = os.getenv("CLICKHOUSE_TRACE_COSTS_TABLE")
CLICKHOUSE_EVALUATIONS_TABLE = os.getenv("CLICKHOUSE_EVALUATIONS_TABLE")
CLICKHOUSE_SECURITY_TABLE    = os.getenv("CLICKHOUSE_SECURITY_TABLE")
CLICKHOUSE_AUDIT_TABLE       = os.getenv("CLICKHOUSE_AUDIT_TABLE", "audit_log")
AUDIT_HMAC_SECRET            = os.getenv("AUDIT_HMAC_SECRET", "change-me-in-production")

REDIS_URL = os.getenv("REDIS_URL")
REDIS_SDK_URL = os.getenv("REDIS_SDK_URL") or REDIS_URL
REDIS_DEFAULT_TTL_SECONDS = int(os.getenv("REDIS_DEFAULT_TTL_SECONDS"))

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
 
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
API_BASE_URL = os.getenv("API_BASE_URL")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

KAFKA_SECURITY_REPLY_TOPIC     = os.getenv("KAFKA_SECURITY_REPLY_TOPIC")
KAFKA_SECURITY_CHECK_TIMEOUT   = float(os.getenv("KAFKA_SECURITY_CHECK_TIMEOUT"))

KAFKA_PLAYGROUND_REPLY_TOPIC   = os.getenv("KAFKA_PLAYGROUND_REPLY_TOPIC")
KAFKA_PLAYGROUND_CHECK_TIMEOUT = float(os.getenv("KAFKA_PLAYGROUND_CHECK_TIMEOUT", "30"))