services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluiq-api
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_started
      postgres:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - fluiq-ai
    restart: unless-stopped

networks:
  fluiq-ai:
    external: true
    name: fluiq-ai
